#!/bin/sh

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#       (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#           noncompliant, but you have some other compliant shell such as ksh or
#           bash, then to run this script, type that shell name before the whole
#           command line, like:
#
#               ksh Gradle
#
#           Busybox and similar reduced shells will NOT work, because this script
#           requires all of these POSIX shell features:
#             * functions;
#             * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#               «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#             * compound commands having a testable exit status, especially «case»;
#             * various built-in commands including «command», «set», and «ulimit».
#
#           Important for patching:
#
#           (2) This script targets any POSIX shell, so it avoids extensions provided
#               by Bash, Ksh, etc; in particular arrays are avoided.
#
#               The "traditional" practice of packing multiple parameters into a
#               space-separated string is a well documented source of bugs and security
#               problems, so this is (mostly) avoided, by progressively accumulating
#               options in "$@", and eventually passing that to Java.
#
#               Where the inherited environment variables (DEFAULT_JVM_OPTS, JAVA_OPTS,
#               and GRADLE_OPTS) rely on word-splitting, this is performed explicitly;
#               see the in-line comments for details.
#
#               There are tweaks for specific operating systems such as AIX, CygWin,
#               Darwin, MinGW, and NonStop.
#
#           (3) This script is generated from the Groovy template
#               https://github.com/gradle/gradle/blob/HEAD/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
#               within the Gradle project.
#
#               You can find Gradle at https://github.com/gradle/gradle/.
#
##############################################################################

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

case "$(uname)" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

if [ "$cygwin" = "true" -o "$msys" = "true" ] ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )
    
    JAVACMD=$( cygpath --unix "$JAVACMD" )

    set -- \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

    exec "$JAVACMD" "$@"
fi

if [ "$darwin" = true ] ; then
    MAX_FD=unlimited
fi

if [ "$nonstop" = true ] ; then
    unset _JAVA_OPTIONS
    GRADLE_OPTS="$GRADLE_OPTS \"-Xms512m\" \"-Xmx512m\""
fi

if [ "$darwin" != true -a "$nonstop" != true ] ; then
    case $MAX_FD in
      max*)
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in
      '' | soft) :;;
      *)
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit: $MAX_FD"
    esac
fi

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS '"-Dorg.gradle.appname=$APP_BASE_NAME"' '-classpath "$CLASSPATH"' org.gradle.wrapper.GradleWrapperMain '"$@"'

exec "$JAVACMD" "$@"
